title: adillash
theme: minima
author: Adill Ashidiq
email: nothingimportant200@gmail.com
description: > # this means to ignore newlines until "baseurl:"
yo blblalbalblablalblablablablablablablaallablalablalalbalbblabla delsoon

# social links
twitter_username: adillash # DO NOT include the @ character, or else the build will fail!
github_username:  adillashidiq # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
